### ISSUE TITLE
Fix unfair display of territories in private.

### ISSUE THREAD

**Issue by 79372275372** [TownyAdvanced/MapTowny#22]
When a player claims territory on the perimeter and does not claim it inside - the territory is displayed on the map as if it fully belongs to him.
Example - https://imgur.com/a/IXpzQIV

**Comment by silverwolfg11** [comment]
I think you meant to file this as a bug, so I fixed the label for you.

Can you please also provide the following information:
- Plugin Version (I assume you're using the latest which is 2.0.0-BETA-2)
- Web-Map Plugin Version (E.g. SquareMap #233, etc)
- Towny Version
- Server Software Version

I also want to note that if you're using either Dynmap or BlueMap, this is an issue that cannot be fixed because those platforms do not support the concept of negative space (having holes within the claim).

**Comment by 79372275372** [comment]
> I use:
> 
> * 2.0.0-BETA-2
> * dynmap las build
> * towny 0.97.2.0
> * 1.16.5

**Comment by silverwolfg11** [comment]
@PolitcubesDeveloper Thank you for the suggestions. I'll be sure to take a look into those algorithms and see if I can get them to work on Dynmap/BlueMap for this use case. 

However, I'll create this as a separate issue as an enhancement since this current issue is not a bug, but that of a non-existing feature.

Currently, the plugin does not support holes in polygons for BlueMap/Dynmap, so this issue will be closed.
