### ISSUE TITLE
MapTowny NPE spam

### ISSUE THREAD

**Issue by ItsSynchro** [TownyAdvanced/MapTowny#26]
## Describe the Bug
For context, I use Geyser on my server which is online mode. I recently changed the Geyser prefix option from being an underscore to the * symbol. I've changed the regex option in Towny to make it compatible however after switching I've noticed that the MapTowny error I've provided started appearing.

https://paste.gg/p/anonymous/3ff6f0b833664271984f9a9a661cffb2

## Expected Behavior

Compatibility with Geyser name changes (sorta assume that might be why?)

### Plugin Version

MapTowny-2.0.0-BETA-1

### Towny Version
Towny-0.98.1.0

### Pl3xMap Version
squaremap-paper-mc1.18.2-1.1.3

### Server Software Version

Pufferfish 1.18.2

## Additional Comments

My online map can be found here https://thecavern.net/map/

**Comment by silverwolfg11** [comment]
Hey, sorry for the late response. 

It looks like for some reason Towny is not returning a UUID (unique identifier) for some of your towns. Since MapTowny makes the assumption that a town will always have a UUID (which theoretically as per Towny should be a valid assumption) and a town doesn't, MapTowny doesn't know what to do. 

In short, this is most likely a Towny bug rather than a MapTowny bug, so I'm going to go ahead and close this issue. 

If you're still getting this issue on the latest versions of Towny and MapTowny, create another issue and we can take a deeper look.
