### ISSUE TITLE
Error changing the %mayor%

### ISSUE THREAD

**Issue by r0xANDt0l** [TownyAdvanced/MapTowny#30]
## Describe the Bug
Error changing the %mayor%
### Plugin Version
2.0.0
### Towny Version
0.98.3.0
### Dynmap Version
3.4 beta 4
### Server Software Version

pufferfish 1.18.2 R0.1

## Additional Comments
* Startup: https://gist.github.com/r0xANDt0l/f0a826df2a513880fb7101e6701cecfa
* Config: https://gist.github.com/r0xANDt0l/ad91c10f09c9a9b8a362897aee37ae57

**Comment by silverwolfg11** [comment]
It seems like the town `Slithercentre` has an invalid mayor (or no mayor) set. This can probably be fixed by either manually setting a mayor, or if you have experience with this, changing it directly in the Towny data. 

Regardless, this is a Towny issue (mayors are expected to always be valid), so I will close this issue.
