### ISSUE TITLE
Blue stripes in web view

### ISSUE THREAD

**Issue by Folas1337** [TownyAdvanced/MapTowny#32]
## Describe the Bug
There are blue, horizontal lines rendering on towns of different sizes and shapes, it doesn't appear to happen to all towns though.

## Expected Behavior
No such lines.

### Plugin Version
2.0.1

### Towny Version
0.98.3.0

### squaremap Version
1.1.6 (I've changed it to say squaremap)

### Server Software Version
Paper 1.19 build 77

## Additional Comments
Here's a close up of one:
![Screenshot_20220806-104958~2.png](https://user-images.githubusercontent.com/39222968/183242458-2bc8b743-a3ce-44e9-9a69-b7b82e9e17cb.png)

And here are several ones:
![Screenshot_20220806-105025~4.png](https://user-images.githubusercontent.com/39222968/183242419-d7ba208c-3a3b-49f5-96d1-6c95b599d25e.png)

**Comment by silverwolfg11** [comment]
I'm not really sure what could be causing this issue. 

Here are some questions that may help hone in on the issue:

Do the towns with the blue lines have home markers? If not, those blue lines could be a weird rendering of the home marker maybe due to the icon size?

Do you notice any pattern to the blue lines? Do the blue lines still occur if you switch to a different web-map plugin (e.g. Pl3xMap) or an older version of squaremap?

**Comment by Folas1337** [comment]
> I'm not really sure what could be causing this issue.
> 
> Here are some questions that may help hone in on the issue:
> 
> Do the towns with the blue lines have home markers? If not, those blue lines could be a weird rendering of the home marker maybe due to the icon size?
> 
> Do you notice any pattern to the blue lines? Do the blue lines still occur if you switch to a different web-map plugin (e.g. Pl3xMap) or an older version of squaremap?

Oh yeah, you gave me the right hint... I had "icon-info.icon-height: 35" and "icon-info.icon-width: 1" in the config which resulted in this funny stripe. I've now set both to 0 and they seem to have disappeared.

User error, I apologize and thank you for pointing me in the right direction 👍 
Issue closed!
